# Generated by Django 4.2 on 2023-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('Amount', models.IntegerField()),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
